version: '3.3'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - kafka:/kafka
    depends_on:
    - zookeeper
    healthcheck:
      test:
      - CMD-SHELL
      - cub kafka-ready -b kafka:9092 1 30 && exit 0 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    ports:
    - 127.0.0.1:${ZOOKEEPER_PORT:-2181}:2181
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    volumes:
    - zookeeper:/zookeeper
    platform: linux/amd64

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
    - 127.0.0.1:${KAFKA_UI_PORT:-8082}:${KAFKA_UI_PORT:-8082}
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      SERVER_PORT: ${KAFKA_UI_PORT:-8082}
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${KAFKA_UI_PORT:-8082}/actuator/health

volumes:
  kafka:
  zookeeper: